version: '3.8'
services:
  iot_gateway:
    build: .
    command: ["/app/build/iot_gateway", "--config", "config/iot_gateway_config.yaml"]
    volumes:
      - ./build_iot_gateway:/app/build

    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Europe/Moscow

  ca_service:
    build: .
    command: ["/app/build/ca_service", "--config", "config/ca_service_config.yaml"]
    volumes:
      - ./build_ca_service:/app/build
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Europe/Moscow

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: notification_db
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pg-data: