services:

# ========== Common services
  # common:
  #   container_name: common
  #   depends_on:
  #     - postgres
  #     - redis
  #     - iot_gateway
  #     - ca_service
  #     - back_gateway

# ========== Single Services
  iot_gateway:
    container_name: iot_gateway
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.builder
    command: ["/app/build/iot_gateway/iot_gateway"]
    volumes:
      - ./iot_gateway/config:/app/config
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Europe/Moscow

  ca_service:
    container_name: ca_service
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.builder
    command: ["/app/build/ca_service/ca_service"]
    volumes:
      - ./ca_service/config:/app/config
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Europe/Moscow

  back_gateway:
    container_name: back_gateway
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.builder
    command: ["/app/build/back_gateway/back_gateway"]
    volumes:
      - ./back_gateway/config:/app/config
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - redis
    environment:
      - TZ=Europe/Moscow

# ========== Build service for userver
  userver-latest:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.builder
    container_name: userver-app
    restart: "no"
    depends_on: 
      - postgres
      - redis
    volumes:
      - ./:/app

# ========== Database services
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: server_db
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pg-data: